version: "3.9"

services:
  db:
    image: postgres:15
    profiles: ["dev"]
    environment:
      POSTGRES_DB: municipal_fleet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    profiles: ["dev"]
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn municipal_fleet.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: municipal_fleet.settings.prod
      DJANGO_SECRET_KEY: change-me
      DJANGO_ALLOWED_HOSTS: localhost,backend
      POSTGRES_DB: municipal_fleet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CORS_ALLOW_ALL: "False"
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      DJANGO_SECURE_SSL_REDIRECT: "False"
      SESSION_COOKIE_SECURE: "False"
      CSRF_COOKIE_SECURE: "False"
      CSRF_TRUSTED_ORIGINS: http://localhost:5173,http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
      - frontend_dist:/app/frontend/dist

  frontend:
    image: node:20
    working_dir: /app
    profiles: ["dev"]
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_URL: http://localhost:8001/api
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    shm_size: '2gb'

  frontend-build:
    image: node:20
    working_dir: /app
    profiles: ["prod"]
    command: sh -c "npm install && npm run build"
    environment:
      VITE_API_URL: http://backend:8000/api
      NODE_OPTIONS: "--max-old-space-size=4096"
    volumes:
      - ./frontend:/app
      - frontend_dist:/app/dist
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    shm_size: '4gb'
    privileged: true

  nginx:
    image: nginx:1.25
    profiles: ["prod"]
    depends_on:
      - backend
      - frontend-build
    ports:
      - "8080:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - staticfiles:/app/staticfiles:ro
      - media:/app/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
  staticfiles:
  media:
  frontend_dist:
  frontend_node_modules:
